#include "Enginepch.h"

DEFINE_LOG_CATEGORY(LogGameEngine);
DEFINE_LOG_CATEGORY(LogApplication);
DEFINE_LOG_CATEGORY(LogAudioEngine);
DEFINE_LOG_CATEGORY(LogAudioPlayer);
DEFINE_LOG_CATEGORY(LogDebugDrawer);
DEFINE_LOG_CATEGORY(LogScene);
DEFINE_LOG_CATEGORY(LogSceneHandler);
DEFINE_LOG_CATEGORY(LogSceneLoader);